import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {createApp} from '../server.js';import {createChecker} from '../lookup.js';
const require=createRequire(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/package.json':import.meta.url);const {chromium}=require('playwright');
const engine=createChecker({intervals:{minecraft:0,tiktok:0,snapchat:0},fetchImpl:async url=>url.includes('mojang')?Response.json([]):new Response('',{status:404})});const server=createApp(engine);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process']});const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(base);await page.screenshot({path:new URL('../../desktop.png',import.meta.url).pathname,fullPage:true});assert.equal(await page.locator('#budget').inputValue(),'2000');
 await page.locator('#effort').focus();await page.keyboard.press('End');assert.equal(await page.locator('#budget').inputValue(),'10000');await page.locator('#budget').fill('2000');await page.locator('[name=platform][value=tiktok]').check();assert.equal(await page.locator('#budget').getAttribute('max'),'2000');await page.locator('[name=platform][value=tiktok]').uncheck();await page.locator('[name=platform][value=minecraft]').uncheck();await page.locator('[name=platform][value=discord]').check();
 await page.locator('#budget').fill('10000');await page.locator('#start').click();await page.waitForFunction(()=>document.getElementById('run-state').textContent==='Search complete');assert.equal(await page.locator('#result-count').textContent(),'10,000 matching results · 10,000 total');assert.equal(await page.locator('.result-row').count(),50);assert.equal(await page.locator('#checked').textContent(),'10,000 / 10,000 names checked');assert.equal(await page.locator('#percentage').textContent(),'100%');assert(await page.locator('#retry').isDisabled());
 await page.locator('#next').click();assert.equal(await page.locator('#page-info').textContent(),'Page 2 of 200');await page.locator('#result-query').fill('unlikely_name_zzz');await page.waitForTimeout(250);assert.equal(await page.locator('.result-row').count(),0);assert.equal(await page.locator('#empty-text').textContent(),'No results match this view.');await page.locator('#result-query').fill('');await page.waitForTimeout(250);
 await page.locator('#status-filter').selectOption('Taken');assert.equal(await page.locator('.result-row').count(),0);await page.locator('#status-filter').selectOption('Unknown');assert.equal(await page.locator('.result-row').count(),50);
 // The CSV contains honest statuses, with no fabricated availability.
 const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'four-name-results.csv');
 await page.screenshot({path:new URL('../../results.png',import.meta.url).pathname,fullPage:true});
 // Keyboard tab pattern and exact input list; XSS-shaped names remain inert.
 await page.locator('#generate-tab').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#list-tab').getAttribute('aria-selected'),'true');await page.locator('#status-filter').selectOption('all');await page.locator('#names').fill('Nova\nnova\nbad name\n<script>alert(1)</script>');await page.waitForTimeout(1100);await page.locator('#start').click();await page.waitForFunction(()=>document.getElementById('run-state').textContent==='Search complete');assert.equal(await page.locator('#result-count').textContent(),'3 matching results · 3 total');assert.equal(await page.locator('.result-row script').count(),0);await page.locator('#status-filter').selectOption('all');assert.equal(await page.locator('.result-row').count(),3);
 await page.setViewportSize({width:390,height:844});await page.goto(base);await page.emulateMedia({reducedMotion:'reduce'});await page.screenshot({path:new URL('../../mobile.png',import.meta.url).pathname,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('.energy i').first().evaluate(e=>getComputedStyle(e).animationName),'none');
 assert.deepEqual(errors,[]);console.log('Browser verification passed: 10,000-name search, bounded DOM, pagination, filters, export, keyboard tabs, deduplication, XSS-safe rendering, mobile and reduced motion.');
}catch(error){await page.screenshot({path:new URL('../../browser-failure.png',import.meta.url).pathname,fullPage:true});throw error}finally{await browser.close();server.cancelSearches();server.closeAllConnections();await new Promise(r=>server.close(r))}
