import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {JSDOM} from 'jsdom';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn){const end=Date.now()+5000;while(!fn()){if(Date.now()>end)throw Error('DOM update timed out');await sleep(20)}}
test('original UI, one service, real icons, available-only grid and exports',async()=>{
 const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8'),dom=new JSDOM(html,{url:'http://localhost:3000'}),saved={};const intervals=[];for(const key of ['window','document','matchMedia','fetch','setInterval'])saved[key]=globalThis[key];dom.window.HTMLElement.prototype.scrollIntoView=function(){};globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.matchMedia=()=>({matches:true});globalThis.setInterval=(...args)=>{const id=saved.setInterval(...args);intervals.push(id);return id};let mode='mixed',stall=false;const jobs=[];
 globalThis.fetch=async(url,{body,signal})=>{if(stall)return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}));const job=JSON.parse(body);jobs.push(job);let rows;if(mode==='mixed')rows=[{name:'available_fixture',status:'Available'},{name:'taken_fixture',status:'Taken'},{name:'unknown_fixture',status:'Unknown'},{name:'reserved_fixture',status:'Restricted/Reserved'},{name:'invalid_fixture',status:'Invalid'}];else if(mode==='large')rows=Array.from({length:10000},(_,i)=>({name:'test'+i,status:'Available'}));else rows=[{name:'unknown_fixture',status:'Unknown',code:'unresolved'}];rows=rows.map(r=>({...r,platform:job.platforms[0],reason:'Synthetic UI test fixture; not live availability',checkedAt:new Date().toISOString()}));const events=[{type:'meta',names:job.names.length,total:rows.length}];for(let i=0;i<rows.length;i+=100)events.push({type:'results',rows:rows.slice(i,i+100)});events.push({type:'done'});return new Response(events.map(e=>JSON.stringify(e)).join('\n')+'\n')};
 try{let source=await readFile(new URL('../public/app.js',import.meta.url),'utf8');for(const [web,path] of [['/platforms.js','../platforms.js'],['/generator.js','../public/generator.js'],['/help-data.js','../public/help-data.js'],['/words.js','../public/words.js']])source=source.replace("'"+web+"'",JSON.stringify(new URL(path,import.meta.url).href));await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
 const $=id=>document.getElementById(id),event=type=>new dom.window.Event(type,{bubbles:true}),choose=p=>{const radio=document.querySelector('[name=platform][value='+p+']');radio.click()},submit=()=>{$('search-form').dispatchEvent(event('submit'))};
 assert.equal(document.querySelector('[name=platform]:checked').value,'minecraft');assert.equal(document.querySelectorAll('[name=platform][type=radio]').length,4);assert.equal(document.querySelectorAll('.service-icon').length,4);for(const image of document.querySelectorAll('.service-icon')){assert(image.src.includes('/service-icons/'));assert((await readFile(new URL('../public/service-icons/'+image.src.split('/').at(-1),import.meta.url),'utf8')).includes('<svg'))}
 for(const p of ['tiktok','snapchat','discord','minecraft']){choose(p);assert.equal(document.querySelectorAll('[name=platform]:checked').length,1);assert.equal(document.querySelector('[name=platform]:checked').value,p)}assert.equal(document.querySelector('.tablist'),null);assert.equal($('status-grid'),null);assert.equal(document.querySelector('.result-toolbar'),null);assert.equal($('method'),null);assert.equal($('budget').value,'2000');assert.equal($('length').max,'7');
 $('skip_checked').checked=false;submit();await until(()=>!$('start').disabled&&$('count').textContent==='1');assert.deepEqual(jobs.at(-1).platforms,['minecraft']);assert.equal(document.querySelectorAll('.name').length,1);assert($('result-list').textContent.includes('available_fixture'));for(const name of ['taken_fixture','unknown_fixture','reserved_fixture','invalid_fixture'])assert(!$('result-list').textContent.includes(name));assert(!document.querySelector('.badge'));
 let captured;const originalURL=URL.createObjectURL;URL.createObjectURL=blob=>{captured=blob;return originalURL(blob)};const click=dom.window.HTMLAnchorElement.prototype.click;dom.window.HTMLAnchorElement.prototype.click=function(){};$('export').click();const csv=await captured.text();assert(csv.includes('available_fixture'));assert(!csv.includes('unknown_fixture'));URL.createObjectURL=originalURL;dom.window.HTMLAnchorElement.prototype.click=click;
 mode='large';choose('discord');$('budget').value='10000';$('budget').dispatchEvent(event('input'));const start=performance.now();submit();await until(()=>$('count').textContent==='10,000'&&!$('start').disabled);assert.equal(document.querySelectorAll('.name').length,50);assert(performance.now()-start<3000);$('next').click();assert.equal($('page-info').textContent,'Page 2 of 200');
 mode='unknown';choose('minecraft');submit();await until(()=>$('empty-text').textContent==='No verified available names'&&!$('start').disabled);assert.equal(document.querySelectorAll('.name').length,0);assert.equal($('count').textContent,'0');assert($('export').disabled);assert($('run-state').textContent.includes('Unable to verify availability'));
 stall=true;submit();await until(()=>$('run-state').textContent==='Exploring your names…');$('cancel').click();await until(()=>$('run-state').textContent==='Stopped · results preserved');$('theme').click();assert.equal(document.documentElement.dataset.theme,'light');$('theme').click();assert.equal(document.documentElement.dataset.theme,'dark');$('clear-results').click();assert.equal($('count').textContent,'0');assert.equal(document.querySelector('[name=platform]:checked').value,'minecraft');
 }finally{for(const id of intervals)clearInterval(id);await sleep(150);for(const [key,value] of Object.entries(saved))globalThis[key]=value;dom.window.close()}
});
