import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {JSDOM} from 'jsdom';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){const end=Date.now()+5000;while(!fn()){if(Date.now()>end)throw Error('DOM update timed out');await sleep(20)}}
test('interface: 10,000 results, bounded rendering, exact effort, filters, cancellation and safe text',async()=>{
 const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');const dom=new JSDOM(html,{url:'http://localhost:3000'});const saved={};const intervalIds=[];for(const name of ['window','document','matchMedia','fetch','setInterval'])saved[name]=globalThis[name];
 dom.window.HTMLElement.prototype.scrollIntoView=function(){};globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.matchMedia=()=>({matches:true});globalThis.setInterval=(...args)=>{const id=saved.setInterval(...args);intervalIds.push(id);return id};
 let stall=false,requests=0;const jobs=[];
 globalThis.fetch=async(url,{body,signal})=>{requests++;if(stall)return new Promise((_,reject)=>{signal.addEventListener('abort',()=>reject(signal.reason),{once:true})});const job=JSON.parse(body);jobs.push(job);const rows=job.platforms.flatMap(platform=>job.names.map(name=>({name,platform,status:name.includes(' ')?'Invalid':'Unknown',code:platform==='discord'?'unsupported':'unresolved',reason:'Test fixture only',checkedAt:new Date().toISOString()})));const events=[{type:'meta',names:job.names.length,total:rows.length}];for(let i=0;i<rows.length;i+=100)events.push({type:'results',rows:rows.slice(i,i+100)});events.push({type:'done'});return new Response(events.map(e=>JSON.stringify(e)).join('\n')+'\n')};
 try{
  const source=(await readFile(new URL('../public/app.js',import.meta.url),'utf8')).replace("'/platforms.js'",JSON.stringify(new URL('../platforms.js',import.meta.url).href)).replace("'/generator.js'",JSON.stringify(new URL('../public/generator.js',import.meta.url).href));await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
  const $=id=>document.getElementById(id),event=(type)=>new dom.window.Event(type,{bubbles:true});const fill=(id,value)=>{$(id).value=value;$(id).dispatchEvent(event('input'))};const choose=(p,value)=>{const input=document.querySelector('[name=platform][value='+p+']');input.checked=value;input.dispatchEvent(event('change'))};
  assert.equal($('budget').value,'2000');fill('effort','4');assert.equal($('budget').value,'10000');fill('budget','2345');assert.equal($('budget').value,'2345');choose('tiktok',true);assert.equal($('budget').max,'2000');assert.equal($('budget').value,'2000');choose('tiktok',false);choose('minecraft',false);choose('discord',true);
  fill('budget','10000');const start=performance.now();$('search-form').dispatchEvent(event('submit'));await until(()=>$('run-state').textContent==='Search complete');const elapsed=performance.now()-start;assert.equal($('result-count').textContent,'10,000 matching results · 10,000 total');assert.equal(document.querySelectorAll('.result-row').length,50);assert.equal($('checked').textContent,'10,000 / 10,000 names checked');assert.equal($('percentage').textContent,'100%');assert($('retry').disabled);assert(elapsed<3000);console.log('DOM large-search measurement:',Math.round(elapsed)+'ms, 50 rendered rows');
  $('next').click();assert.equal($('page-info').textContent,'Page 2 of 200');fill('result-query','unlikely___name');await until(()=>!document.querySelectorAll('.result-row').length);assert.equal($('empty').querySelector('h3').textContent,'No results match this view.');fill('result-query','');await until(()=>document.querySelectorAll('.result-row').length===50);$('status-filter').value='Taken';$('status-filter').dispatchEvent(event('change'));assert.equal(document.querySelectorAll('.result-row').length,0);$('status-filter').value='all';$('status-filter').dispatchEvent(event('change'));
  $('generate-tab').dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal($('list-tab').getAttribute('aria-selected'),'true');fill('names','Nova\nnova\nbad name\n<script>alert(1)</script>');$('search-form').dispatchEvent(event('submit'));await until(()=>$('result-count').textContent==='3 matching results · 3 total');assert.equal($('result-count').textContent,'3 matching results · 3 total');assert.equal(document.querySelectorAll('.result-row script').length,0);assert(document.querySelector('#result-list').textContent.includes('<script>alert(1)</script>'));
  choose('discord',false);choose('minecraft',true);fill('names','nova');$('search-form').dispatchEvent(event('submit'));await until(()=>$('checked').textContent==='1 / 1 names checked'&&$('run-state').textContent==='Search complete');assert(!$('retry').disabled);$('retry').click();await until(()=>jobs.at(-1)?.refresh===true&&!$('start').disabled);await until(()=>$('run-state').textContent==='Search complete');
  stall=true;$('search-form').dispatchEvent(event('submit'));await until(()=>$('run-state').textContent==='Exploring your names…');$('cancel').click();await until(()=>$('run-state').textContent==='Stopped · results preserved');assert(!$('start').disabled);assert($('form-error').hidden);assert(requests>=3);
  const css=await readFile(new URL('../public/styles.css',import.meta.url),'utf8');assert(css.includes('@media(prefers-reduced-motion:reduce)'));assert(css.includes('@media(max-width:500px)'));assert(css.includes(':focus-visible'));
 }finally{for(const id of intervalIds)clearInterval(id);await sleep(150);for(const [key,value] of Object.entries(saved))globalThis[key]=value;dom.window.close()}
});
