import {test} from 'node:test';import assert from 'node:assert/strict';import {generateCandidates} from '../public/generator.js';import {createWordMatcher,COMMON} from '../public/word-match.js';import {WORDS} from '../public/words.js';import {createApp} from '../server.js';import {createChecker} from '../lookup.js';import {createRemoteChecker} from '../workers/client.js';import worker,{CheckCoordinator} from '../workers/cloudflare.js';
const signal=()=>new AbortController().signal;
test('exhaustive chunks cover the full filtered Cartesian product across budgets, without omissions',async()=>{
 let cursor='0',all=[],report;do{const names=await generateCandidates({length:4,chars:'letters',allowed:'ab',limit:3,generation_mode:'exhaustive',cursor},()=>false,r=>report=r);all.push(...names);cursor=report.visited}while(!report.complete);assert.equal(all.length,16);assert.equal(new Set(all).size,16);
 const names=await generateCandidates({length:4,chars:'letters',allowed:'ab',limit:100,generation_mode:'exhaustive',contains:'ab',no_adjacent:true});assert.deepEqual(new Set(names),new Set(all.filter(n=>n.includes('ab')&&!/(.)\1/.test(n))));
 const shaped=await generateCandidates({length:4,chars:'letters',allowed:'abc',limit:100,generation_mode:'exhaustive',shape:'aabb'});assert.equal(shaped.length,6);assert(shaped.every(n=>n[0]===n[1]&&n[2]===n[3]&&n[0]!==n[2]));
 const big=await generateCandidates({length:32,chars:'letters',allowed:'ab',limit:2,generation_mode:'exhaustive',cursor:'4294967294'},()=>false,r=>report=r);assert.equal(big.length,2);assert.equal(report.space,'4294967296');assert(report.complete);
});
test('word matcher distinguishes substring, boundaries, positions, vocabulary and optional leetspeak',()=>{
 const f={word_min:3,word_vocab:'common'};assert(createWordMatcher(f,WORDS)('scatter'));assert(!createWordMatcher({...f,word_boundary:'word'},WORDS)('scatter'));assert(createWordMatcher({...f,word_boundary:'word'},WORDS)('cat_12'));assert(!createWordMatcher({...f,word_mode:'whole'},WORDS)('cat12'));assert(createWordMatcher({...f,word_mode:'end'},WORDS)('12cat'));assert(!createWordMatcher({...f,word_mode:'start'},WORDS)('12cat'));assert(!createWordMatcher(f,WORDS)('c4t'));assert(createWordMatcher({...f,word_leet:true},WORDS)('c4t'));const extra=[...WORDS].find(w=>w.length>=3&&!COMMON.has(w));assert(extra);assert(createWordMatcher({word_mode:'whole',word_vocab:'broader'},WORDS)(extra));assert(!createWordMatcher({word_mode:'whole',word_vocab:'common'},WORDS)(extra));
});
test('service rules filter generation consistently, including dots and hyphens',async()=>{
 for(const platform of ['minecraft','discord','lastfm','gitlab']){const rows=await generateCandidates({length:3,chars:'extended',allowed:'a_.-',limit:1000,generation_mode:'exhaustive',platform});assert(rows.length);if(platform==='minecraft')assert(rows.every(n=>/^[a_]+$/.test(n)));if(platform==='discord')assert(rows.every(n=>!n.includes('-')&&!n.includes('..')));if(platform==='lastfm')assert(rows.every(n=>n[0]==='a'&&!n.includes('.')));if(platform==='gitlab')assert(rows.every(n=>n[0]==='a'&&!n.endsWith('.')))}
});
test('static responses compress, revalidate and correctly answer HEAD',async()=>{
 const server=createApp();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{const r=await fetch(base+'/app.js',{headers:{'Accept-Encoding':'br'}});assert.equal(r.headers.get('Content-Encoding'),'br');assert(r.headers.get('Cache-Control').includes('must-revalidate'));assert((await r.text()).includes('generationCursor'));const cached=await fetch(base+'/app.js',{headers:{'If-None-Match':r.headers.get('etag')}});assert.equal(cached.status,304);const head=await fetch(base+'/app.js',{method:'HEAD',headers:{'Accept-Encoding':'gzip'}});assert(+head.headers.get('Content-Length')>0);assert.equal(await head.text(),'');assert.equal((await fetch(base+'/word-match.js')).status,200)}finally{await new Promise(r=>server.close(r))}
});
test('warm checks use bounded larger chunks without further API calls',async()=>{
 let calls=0;const checker=createChecker({fetchImpl:async()=>{calls++;return Response.json({taken:false})},intervals:{discord:0}});const names=Array.from({length:1200},(_,i)=>'name'+i);await checker.check('discord',names,signal());const before=calls,events=[];await checker.run({names,platforms:['discord']},signal(),async e=>events.push(e));assert.equal(calls,before);assert.equal(events.filter(e=>e.type==='results').length,3);assert.equal(events.flatMap(e=>e.rows||[]).length,1200);
});
test('remote checker validates evidence, keeps secrets server-side and rejects Minecraft Available',async()=>{
 const row={name:'abc',platform:'discord',status:'Available',reason:'Explicit fixture',checkedAt:new Date().toISOString()};let body;const checker=createRemoteChecker({url:'https://worker.example/check',secret:'x'.repeat(32),fetchImpl:async(url,options)=>{body=options;return Response.json({rows:[row]})}}),events=[];await checker.run({names:['ABC','abc'],platforms:['discord']},signal(),async e=>events.push(e));assert.equal(body.headers.Authorization,'Bearer '+'x'.repeat(32));assert.equal(events.flatMap(e=>e.rows||[]).length,1);assert.equal(events.at(-1).type,'done');row.platform='minecraft';await assert.rejects(checker.run({names:['abc'],platforms:['minecraft']},signal(),async()=>{}),/Invalid worker evidence/);assert.throws(()=>createRemoteChecker({url:'http://bad.example',secret:'x'.repeat(32)}),/HTTPS/);
});
test('worker authenticates, enforces small batches and persists shared rate gates',async()=>{
 assert.equal((await worker.fetch(new Request('https://test',{method:'POST'}),{})).status,401);const saved=new Map(),ctx={storage:{get:async k=>saved.get(k),put:async(k,v)=>saved.set(k,v)},blockConcurrencyWhile:fn=>fn()};const coordinator=new CheckCoordinator(ctx,{});coordinator.engine=createChecker({fetchImpl:async()=>Response.json([]),intervals:{minecraft:0}});const r=await coordinator.fetch(new Request('https://test',{method:'POST',body:JSON.stringify({platforms:['minecraft'],names:['notch']})}));assert.equal(r.status,200);assert.equal((await r.json()).rows[0].status,'Unknown');assert(saved.get('gates').minecraft);const oversized=await coordinator.fetch(new Request('https://test',{method:'POST',body:JSON.stringify({platforms:['minecraft'],names:Array(11).fill('notch')})}));assert.equal(oversized.status,400);
});
test('Minecraft overlaps two slow requests while retaining one global start gate',async()=>{
 let active=0,max=0;const starts=[];const c=createChecker({intervals:{minecraft:2},fetchImpl:async()=>{starts.push(Date.now());max=Math.max(max,++active);await new Promise(r=>setTimeout(r,25));active--;return Response.json([])}}),events=[];await c.run({names:Array.from({length:40},(_,i)=>'name'+i),platforms:['minecraft']},signal(),async e=>events.push(e));assert.equal(max,2);assert.equal(starts.length,4);for(let i=1;i<starts.length;i++)assert(starts[i]-starts[i-1]>=1);assert.equal(events.filter(e=>e.type==='meta').length,1);assert.equal(events.flatMap(e=>e.rows||[]).length,40);assert.equal(events.at(-1).type,'done');
});
